apiVersion: v1
kind: Namespace
metadata:
  name: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-deployment
  namespace: frontend
  labels:
    app: reactjs-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactjs-app
  template:
    metadata:
      labels:
        app: reactjs-app
    spec:
      containers:
        - name: react-ct
          image: imran177/react-app
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: reactjs-service
  namespace: frontend
  labels:
    app: reactjs-app
    version: v1
spec:
  type: NodePort
  selector:
    app: reactjs-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # NodePort range is typically 30000-32767
